title: 甯哥的博客
subtitle: 全栈开发 | .NET | 个人随想
author: Homlee
language: zh-CN
timezone: Asia/Shanghai

url: https://homleening.github.io
root: /

permalink: :year/:month/:title/
default_layout: post

# 主题
theme: even

# 开启文章资源文件夹
post_asset_folder: true

# 新版Hexo必备，解决相对路径裂图
marked:
  prependRoot: true
  postAsset: true

# 分页
index_generator:
  per_page: 10
  order_by: -date

# 部署
deploy:
  type: git
  repo: https://github.com/homleening/homleening.github.io.git
  branch: main